apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"jaeger"},"name":"jaeger","namespace":"tracing"},"spec":{"ports":[{"name":"collection","port":14268},{"name":"ui","port":16686},{"name":"grpc","port":14250}],"selector":{"app":"jaeger"}}}
  creationTimestamp: "2020-04-21T19:23:39Z"
  labels:
    app: jaeger
  name: jaeger
  namespace: tracing
  resourceVersion: "524431"
  selfLink: /api/v1/namespaces/tracing/services/jaeger
  uid: 44a2d642-3c92-492a-a671-687e9d106eeb
spec:
  clusterIP: 10.63.245.171
  ports:
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  - name: collection
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: ui
    port: 16686
    protocol: TCP
    targetPort: 16686
  - name: grpc
    port: 14250
    protocol: TCP
    targetPort: 14250
  selector:
    app: jaeger
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
