apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"jaeger"},"name":"jaeger","namespace":"tracing"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"jaeger"}},"template":{"metadata":{"labels":{"app":"jaeger"}},"spec":{"containers":[{"image":"jaegertracing/all-in-one:1.8","name":"jaeger","ports":[{"containerPort":14268,"name":"collection"},{"containerPort":16686,"name":"ui"},{"containerPort":14250,"name":"grpc"}],"resources":{"limits":{"cpu":"500m","memory":"500Mi"},"requests":{"cpu":"200m","memory":"100Mi"}}}],"dnsPolicy":"ClusterFirst"}}}}
    kubernetes.io/change-cause: kubectl set image deploy jaeger jaeger=jaegertracing/all-in-one:1.17
      --record=true
  creationTimestamp: "2020-04-21T19:23:39Z"
  generation: 8
  labels:
    app: jaeger
  name: jaeger
  namespace: tracing
  resourceVersion: "534461"
  selfLink: /apis/apps/v1/namespaces/tracing/deployments/jaeger
  uid: 1de7b206-1876-48a7-907c-24f696172e1c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jaeger
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        config.linkerd.io/trace-collector: otel-collector.tracing:55678
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: jaeger
    spec:
      containers:
      - args:
        - --log-level
        - debug
        - --collector.zipkin.http-port
        - "9411"
        image: jaegertracing/all-in-one:1.17
        imagePullPolicy: IfNotPresent
        name: jaeger
        ports:
        - containerPort: 14268
          name: collection
          protocol: TCP
        - containerPort: 9411
          name: zipkin
          protocol: TCP
        - containerPort: 16686
          name: ui
          protocol: TCP
        - containerPort: 14250
          name: grpc
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-22T12:03:12Z"
    lastUpdateTime: "2020-04-22T12:03:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-21T19:23:39Z"
    lastUpdateTime: "2020-04-22T22:34:42Z"
    message: ReplicaSet "jaeger-5677bfdf5c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
