apiVersion: v1
data:
  otel-agent-config: |
    receivers:
      opencensus:
        keepalive:
          server_parameters:
            max_connection_age: 120s
            max_connection_age_grace: 30s
      zipkin:
        endpoint: "localhost:9411"
    processors:
      queued_retry:
        num_workers: 16
        queue_size: 10000
        retry_on_failure: true
      batch:
        send_batch_size: 1024
        timeout: 5s
    extensions:
      health_check: {}
    exporters:
      logging:
        loglevel: debug
      jaeger_grpc:
        endpoint: jaeger.tracing:14250
      zipkin:
        url: "http://jaeger.tracing:9411/api/v2/spans"
    service:
      extensions: [health_check]
      pipelines:
        traces/1:
          receivers: [opencensus, zipkin]
          processors: [batch, queued_retry]
          exporters: [jaeger_grpc, logging, zipkin]
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"otel-agent-config":"receivers:\n  opencensus:\n    keepalive:\n      server_parameters:\n        max_connection_age: 120s\n        max_connection_age_grace: 30s\n  zipkin:\n    endpoint: \"localhost:9411\"\nprocessors:\n  queued_retry:\n    num_workers: 16\n    queue_size: 10000\n    retry_on_failure: true\n  batch:\n    send_batch_size: 1024\n    timeout: 5s\nextensions:\n  health_check: {}\nexporters:\n  logging:\n    loglevel: debug\n  jaeger_grpc:\n    endpoint: jaeger.tracing:14250\n  zipkin:\n    url: \"http://jaeger.tracing:9411/api/v2/spans\"\nservice:\n  extensions: [health_check]\n  pipelines:\n    traces/1:\n      receivers: [opencensus, zipkin]\n      processors: [batch, queued_retry]\n      exporters: [jaeger_grpc, logging, zipkin]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"opentelemetry","component":"otel-agent-conf"},"name":"otel-agent-conf","namespace":"tracing"}}
  creationTimestamp: "2020-04-22T21:20:27Z"
  labels:
    app: opentelemetry
    component: otel-agent-conf
  name: otel-agent-conf
  namespace: tracing
  resourceVersion: "509429"
  selfLink: /api/v1/namespaces/tracing/configmaps/otel-agent-conf
  uid: 940ff3bb-8518-4b68-95c3-308007b71863
