apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"opencensus","component":"otel-collector"},"name":"otel-collector","namespace":"tracing"},"spec":{"ports":[{"name":"opencensus","port":55678,"protocol":"TCP","targetPort":55678},{"name":"zipkin","port":9411},{"name":"metrics","port":8888}],"selector":{"component":"otel-collector"}}}
  creationTimestamp: "2020-04-22T21:51:01Z"
  labels:
    app: opencensus
    component: otel-collector
  name: otel-collector
  namespace: tracing
  resourceVersion: "519434"
  selfLink: /api/v1/namespaces/tracing/services/otel-collector
  uid: 5b32af69-8809-40e9-85d2-47757a8d0dc3
spec:
  clusterIP: 10.63.246.86
  ports:
  - name: opencensus
    port: 55678
    protocol: TCP
    targetPort: 55678
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  - name: metrics
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    component: otel-collector
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
