apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: echo
  namespace: echo
spec:
  service: server
  backends:
  - service: server
    weight: 50
  - service: server-east
    weight: 50