apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-client
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - hashicorp-consul-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-client-binding
roleRef:
  kind: ClusterRole
  name: consul-client
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize specific service accounts:
- kind: ServiceAccount
  name: hashicorp-consul-client
  namespace: linkerd
