apiVersion: v1
kind: Namespace
metadata:
  name: n8n
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n
  namespace: n8n
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  selector:
    matchLabels:      
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      serviceAccountName: n8n
      containers:
        - name: n8n
          image: n8nio/n8n:0.138.0
          ports:
          - name: http
            containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
spec:
  selector:
    app: n8n
  ports:
  - name: http
    port: 5678
    targetPort: 5678          
    