apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"emojivoto"}}
    linkerd.io/inject: enabled
  creationTimestamp: "2020-04-21T19:37:21Z"
  name: emojivoto
  resourceVersion: "531167"
  selfLink: /api/v1/namespaces/emojivoto
  uid: e4063096-f3a3-43cb-b282-ecb4353594f7
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
