apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminode
spec:
  selector:
    matchLabels:
      app: terminode
  replicas: 1
  template:
    metadata:
      labels:
        app: terminode
    spec:
      containers:
      - name: terminode
        image: ghcr.io/cpretzer/bb-node:v0.1.0
        resources:
          limits:
            memory: 25Mi
            cpu: 500m
          requests:
            memory: 5Mi
            cpu: 100m
        command:
        - /nodejs/bin/node
        - index.js
        - terminus
        - "3000"
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name:  terminode
spec:
  selector:
    app:  terminode
  type:  NodePort
  ports:
  - name:  http
    port:  3000
    targetPort:  3000