apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNREV3TWpneApOek13TWpKYUZ3MDBNREV3TWpneE56TXdNakphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEUHNTUGd2MmswaCtjbXFiSXZFbkphQkdxTUlDNUJGZ0R4SnBYOHZpTW5ITFVma1dwUQo0VGhpU1lrWDJHQTViY29MUlp5RU1RQkUxVEJYdXRndzFiWE44em42Sk9CVWVPWUZIMU9sMi9SS1l2Z2thK1V2Cmg3ckR0cEdhaW9IVnRsRkR3M2JaQXd6NXU1TVAzL0VrRmdwY1MxQk11dDR2QkdFcldmKzg1WE9pRTZ2S2Y3VmQKa3lkSHJXNXZQdUlFaUFKZTg0cU1GVTAzQzlqQ21sa0FzSDdheWtRVFlnMHBUWVFUbW1Sb3dIaHNybG80N1BFZAp2ZlkxZjRWQU9XWnV3YTE3Z09yazZPUVFxWEZvUWs1WCt4MStjMldXdzFJZkxxaE9CK3dNclR1dWdSOUtTVk51CmZHcm9PMHp5K2NVZnRwSWgvNGw5SFdtVkxqOTVsRkVDN2R4MUFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlIzQUltWFN5V2xReTVoT3IvRgppZWVVR1R0S1J6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFtcVFWYklFNS8wU29jeWJWUnZIQllIN3ZPRWFUCjI2WEpuOFdkeWZpRDdRODdBV0pRSWtuNWhHTnduTVBEcjlrV1FzY2VGbTlWL2xQWm9qbmliaDljT1Q5Wkl2a1UKbmp3VWJMd0RFU2ZTTDZqMHh6SThLQm55SDFIMCsvNzZBNEllTlg5aWtOeVRlQ1dNenE5QzhMbVRsQU56RmJpRgpPQlR1ZDh5ekdUUkhjZ1I2T2NNVlpjZ2k3c3BWbGNUVkN3RnZoTEQ0N3hweklIY25oaE8zVXdHdlE3eFJGejEzCmFRUUxtaFgrcDZGRWNTUmYydFBiNnV3NjVLc2dMSWhBZGd2d0MxcTZMVTJBZmZyc0dXM0h4cGRxYkJqc0hzVFMKZ2xoaGRSMHVDQmVQYmwwWTJSOG1LL29LL3VFSTFHTm83aG4yV2xVN1RXL1FONTh4Sm5XZmRocDhPUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://8365166f-1108-4d16-8950-15cbdaaaebcb.k8s.ondigitalocean.com
  name: do-sfo2-east
contexts:
- context:
    cluster: do-sfo2-east
    user: do-sfo2-east-admin
  name: east
current-context: east
kind: Config
preferences: {}
users:
- name: do-sfo2-east-admin
  user:
    token: 68ba507cde568bea8401f02dd0fade42b1738a7526c43160ce5b973cc23b1958
